// <auto-generated />
namespace OnlineMonitoringLog.UI_WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class LogVariableTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LogVariableTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202005301334005_LogVariableTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
